using ApartmentManagementSystem.Domain.Constants;
using ApartmentManagementSystem.Domain.Entities;
using ApartmentManagementSystem.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace ApartmentManagementSystem.Infrastructure.Persistence
{
    /// <summary>
    /// Runtime database seeder called at application startup.
    ///
    /// Seeds roles and SuperAdmin user using role NAMES as the uniqueness key.
    /// No hardcoded GUIDs anywhere — the database generates IDs via Guid.NewGuid().
    ///
    /// Safe to run on every startup because every operation is guarded
    /// by an AnyAsync() existence check before inserting.
   /// SuperAdmin seeding depends on roles already existing.
    /// </summary>
    public class DatabaseSeeder
    {
        private readonly AppDbContext DBContext;

        public DatabaseSeeder(AppDbContext context)
        {
            DBContext = context;
        }

        /// <summary>
        /// Entry point. Called from Program.cs after database migration.
        /// </summary>
        public async Task SeedAsync()
        {
            await SeedRolesAsync();
            await SeedSuperAdminAsync();
        }

        //  Seed Roles

        /// <summary>
        /// Inserts all system roles if they do not already exist.
        ///
        /// Uniqueness check: role NAME (not ID).
        /// ID is generated by Guid.NewGuid() — never hardcoded.
        /// Running this multiple times is completely safe.
        /// </summary>
        private async Task SeedRolesAsync()
        {
            var rolesToSeed = new List<(string Name, string Description)>
            {
                // System Roles
                (RoleNames.SuperAdmin, RoleMessages.SuperAdminMessage),
                (RoleNames.Manager, RoleMessages.ManagerSeedingSuccess),

                // Community Roles
                (RoleNames.President,RoleMessages.PresidentSeededSuccess),
                (RoleNames.Secretary,RoleMessages.SecretarySeededMessage),
                (RoleNames.Treasurer, RoleMessages.TreasurerSeededSuccess),

                // Resident Roles
                (RoleNames.ResidentOwner, RoleMessages.OwnerSeedingSuccess),
                (RoleNames.Tenant, RoleMessages.TenantSeedingMessage),

                // Staff Roles
                (RoleNames.Security,RoleMessages.SecuritySeedingSuccess),
                (RoleNames.Plumber, RoleMessages.PlumberSeeded),
                (RoleNames.Electrician,RoleMessages.ElectricianSeeded),
                (RoleNames.Carpenter,  RoleMessages.CarpenterSeeded),
                (RoleNames.Sweeper, RoleMessages.CleaningStaffSeeded),
                (RoleNames.Gardener, RoleMessages.GardeningStaffSeeded),
                (RoleNames.MaintenanceStaff,RoleMessages.MaintenanceStaffSeeded)
            };

            foreach (var (name, description) in rolesToSeed)
            {
                var exists = await DBContext.Roles.AnyAsync(r => r.Name == name);

                if (!exists)
                {
                    DBContext.Roles.Add(new Role
                    {
                        Id = Guid.NewGuid(),  // DB decides the ID — not us
                        Name = name,
                        Description = description,
                        CreatedAt = DateTime.UtcNow
                    });
                }
            }

            await DBContext.SaveChangesAsync();
        }

        // Seed SuperAdmin 

        /// <summary>
        /// Creates the default SuperAdmin user if one does not already exist.
        ///
        /// Looks up the SuperAdmin role by NAME — not by any hardcoded GUID.
        /// Uniqueness check: admin email address.
        ///
        /// IMPORTANT: Change the default password immediately after first login.
        /// </summary>
        private async Task SeedSuperAdminAsync()
        {
            const string adminEmail = "admin@apartment.com";

            // checking if admin already exists
            if (await DBContext.Users.AnyAsync(u => u.Email == adminEmail))
                return;

            // Find role by NAME 
            var superAdminRole = await DBContext.Roles
                .FirstOrDefaultAsync(r => r.Name == RoleNames.SuperAdmin)
                ?? throw new InvalidOperationException(
                    $"Role '{RoleNames.SuperAdmin}' not found in database. " +
                   RoleMessages.SeedRolesMessage);

            var adminUser = new User
            {
                Id = Guid.NewGuid(),
                FullName = "System Administrator",
                Username = "admin",
                PasswordHash = BCrypt.Net.BCrypt.HashPassword("Admin@123"),
                PrimaryPhone = "9999999999",
                Email = adminEmail,
                IsActive = true,
                IsOtpVerified = true,
                IsRegistrationCompleted = true,
                CreatedAt = DateTime.UtcNow
            };

            DBContext.Users.Add(adminUser);

            // Role ID comes from the DB row we just looked up — not a constant
            DBContext.Set<UserRole>().Add(new UserRole
            {
                Id = Guid.NewGuid(),
                UserId = adminUser.Id,
                RoleId = superAdminRole.Id,
                AssignedAt = DateTime.UtcNow
            });

            await DBContext.SaveChangesAsync();
        }
    }
}






















/*

using ApartmentManagementSystem.Domain.Entities;
using ApartmentManagementSystem.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace ApartmentManagementSystem.Infrastructure.Persistence;

public class DatabaseSeeder
{
    private readonly AppDbContext DBContext;

    public DatabaseSeeder(AppDbContext context)
    {
        DBContext = context;
    }

    public async Task SeedAsync()
    {
        // Seed all roles from UserRole enum
        await SeedRolesAsync();
    }

    private async Task SeedRolesAsync()
    {
        var rolesToSeed = new List<(string Name, string Description)>
        {
            // System Roles
            (RoleNames.SuperAdmin, "Super Administrator with full system access"),
            (RoleNames.Manager, "Manager with administrative privileges"),
            
            // Community Roles
            (RoleNames.President, "Community President - Leadership role"),
            (RoleNames.Secretary, "Community Secretary - Administrative role"),
            (RoleNames.Treasurer, "Community Treasurer - Financial management role"),
            
            // Resident Roles
            (RoleNames.ResidentOwner, "Resident Owner of the flat"),
            (RoleNames.Tenant, "Tenant renting the flat"),
            
            // Staff Roles
            (RoleNames.Security, "Security personnel"),
            (RoleNames.Plumber, "Plumber staff"),
            (RoleNames.Electrician, "Electrician staff"),
            (RoleNames.Carpenter, "Carpenter staff"),
            (RoleNames.Sweeper, "Cleaning staff"),
            (RoleNames.Gardener, "Gardening staff"),
            (RoleNames.MaintenanceStaff, "General maintenance staff")
        };

        foreach (var (name, description) in rolesToSeed)
        {
            var exists = await DBContext.Roles.AnyAsync(r => r.Name == name);

            if (!exists)
            {
                DBContext.Roles.Add(new Role
                {
                    Id = Guid.NewGuid(),
                    Name = name,
                    Description = description,
                    CreatedAt = DateTime.UtcNow
                });
            }
        }

        await DBContext.SaveChangesAsync();
    }
}
*/